# Mirror endpoints. Keep paths free of a trailing slash.
UBUNTU_MIRROR="https://ir.archive.ubuntu.com"
ALMALINUX_MIRROR="https://mirror.hostbaran.com/almalinux"
EPEL_MIRROR="https://mirror.hostbaran.com/epel"
MARIADB_MIRROR="https://mirror.hostbaran.com/mariadb"
CLOUDLINUX_MIRROR="https://mirror.hostbaran.com/cloudlinux"
